<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="docbook" nsURI="http://docbook" nsPrefix="docbook">
  <eClassifiers xsi:type="ecore:EClass" name="DocBook">
    <eStructuralFeatures xsi:type="ecore:EReference" name="book" eType="#//Book" eOpposite="#//Book/docBook"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Book">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="docBook" lowerBound="1"
        eType="#//DocBook" eOpposite="#//DocBook/book"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="article" lowerBound="1"
        upperBound="-1" eType="#//Article" eOpposite="#//Article/book"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" lowerBound="1"
        upperBound="-1" eType="#//Author"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Article">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="book" lowerBound="1" eType="#//Book"
        eOpposite="#//Book/article"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" lowerBound="1"
        upperBound="-1" eType="#//Author"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Author">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
